version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: "#Ovelha354"
      MYSQL_DB: registro_onepiece

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "#Ovelha354"
      MYSQL_DATABASE: registro_onepiece
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
