services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_DB: "registro_onepiece"
    command: ["sh", "-c", "sleep 10 && python app.py"]

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "#Ovelha354"
      MYSQL_DATABASE: "registro_onepiece"
    volumes:
      - ./users_OPB.sql:/docker-entrypoint-initdb.d/users_OPB.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

